name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    name: Linting
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
          python-version:
            - 3.7
            - 3.8
            - 3.9
    steps:
      - name: Install python3-rpm
        run: sudo apt-get install python3-rpm
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v1
      - name: Enable dist-packages in venv
        run: echo "/usr/lib/python3/dist-packages" > .venv/lib/python${{ matrix.python-version }}/site-packages/dist-packages.pth
      - name: Check with black, pylint and pontos.version
        uses: greenbone/actions/lint-python@v1
        with:
          packages: notus tests

  test:
    name: Run all tests
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
          python-version:
            - 3.7
            - 3.8
            - 3.9
    steps:
      - name: Install python3-rpm
        run: sudo apt-get install python3-rpm
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v1
      - name: Enable dist-packages in venv
        run: echo "/usr/lib/python3/dist-packages" > .venv/lib/python${{ matrix.python-version }}/site-packages/dist-packages.pth
      - name: Run unit tests
        run: poetry run python -m unittest

  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install python3-rpm
        run: sudo apt-get install python3-rpm
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v1
      - name: Enable dist-packages in venv
        run: echo "/usr/lib/python3/dist-packages" > .venv/lib/python${{ matrix.python-version }}/site-packages/dist-packages.pth
      - name: Calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v1

