name: Container Image Builds

on:
  push:
    branches: [ main ]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  images:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Gather container image tags
        id: container
        uses: greenbone/actions/container-image-tags@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v1
        with:
          version: 3.9
      - name: Build wheel
        run: poetry build -f wheel
      - name: Build and push Container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.container.outputs.image-tags }}
          file: .docker/notus-scanner.Dockerfile
          labels: |
            org.opencontainers.image.vendor=Greenbone
            org.opencontainers.image.revision=${{ github.sha }}
